// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAuZRjWt8MyIR0CT1cakEn1abUJEwX3L0',
    appId: '1:443645686666:web:08f311eef4caf158610e73',
    messagingSenderId: '443645686666',
    projectId: 'chat-app-e2574',
    authDomain: 'chat-app-e2574.firebaseapp.com',
    storageBucket: 'chat-app-e2574.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVInquJjO7gQwn7r0EMjFp9zpZhxNrHGs',
    appId: '1:443645686666:android:3cc659b8aaf66eae610e73',
    messagingSenderId: '443645686666',
    projectId: 'chat-app-e2574',
    storageBucket: 'chat-app-e2574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4hpU3qvvNG2OwmmVjrj6O5uXBDqBre4',
    appId: '1:443645686666:ios:b9f824c6b3798c56610e73',
    messagingSenderId: '443645686666',
    projectId: 'chat-app-e2574',
    storageBucket: 'chat-app-e2574.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4hpU3qvvNG2OwmmVjrj6O5uXBDqBre4',
    appId: '1:443645686666:ios:3e85c837136873d6610e73',
    messagingSenderId: '443645686666',
    projectId: 'chat-app-e2574',
    storageBucket: 'chat-app-e2574.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
